api-version: '1.21'
depend:
- WorldGuard
name: StaffTolls
main: fun.jaobabus.stafftolls.StaffTolls
version: 1.2-SNAPSHOT
commands:
  feed:
    default: op
    usage: '/feed  [player: Player]'
    description: null
  bungeesend:
    default: op
    usage: '/bungeesend  <command: String> <data: String>'
    description: null
  fly:
    default: op
    usage: '/fly  [player: Player] [state: String]'
    description: null
  gm:
    default: op
    usage: '/gm  <mode: Long> [player: Player]'
    description: null
  heal:
    default: op
    usage: '/heal  [player: Player]'
    description: null
  nv:
    default: op
    usage: '/nv  [player: Player]'
    description: null
  back:
    default: op
    usage: '/back  <pos: BackPositionArgument$Position>'
    description: null
  speed:
    default: op
    usage: '/speed  [speed: Double = 1] [player: Player] [mode: String = auto]'
    description: null
